[2018-09-21 15:46:53][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-21 15:47:18][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 15:47:18] "GET /upload HTTP/1.1" 405 -
[2018-09-21 15:47:18][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 15:47:18] "GET /favicon.ico HTTP/1.1" 404 -
[2018-09-21 15:47:33][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 15:47:33] "GET / HTTP/1.1" 404 -
[2018-09-21 15:47:51][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 15:47:51] "GET /upload HTTP/1.1" 405 -
[2018-09-21 15:49:42][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-21 15:49:49][log.py][line:46][INFO] {"msg":"POST请求,携带的参数不是 file "}
[2018-09-21 15:49:49][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 15:49:49] "GET /upload HTTP/1.1" 200 -
[2018-09-21 15:50:13][log.py][line:46][INFO] {"msg":"POST请求,携带的参数不是 file "}
[2018-09-21 15:50:13][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 15:50:13] "GET /upload HTTP/1.1" 200 -
[2018-09-21 15:50:17][log.py][line:46][INFO] {"msg":"POST请求,携带的参数不是 file "}
[2018-09-21 15:50:17][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 15:50:17] "GET /upload HTTP/1.1" 200 -
[2018-09-21 15:57:56][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-21 15:58:06][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 15:58:06] "GET /upload HTTP/1.1" 200 -
[2018-09-21 16:16:06][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 16:16:06] "GET /upload HTTP/1.1" 200 -
[2018-09-21 16:16:20][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-21 16:16:24][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 16:16:24] "GET /upload HTTP/1.1" 200 -
[2018-09-21 17:44:08][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-21 17:44:11][_internal.py][line:88][INFO] 172.18.104.228 - - [21/Sep/2018 17:44:11] "GET /upload HTTP/1.1" 200 -
[2018-09-25 08:41:30][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-25 17:30:15][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-26 17:14:30][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-26 17:14:42][_internal.py][line:88][INFO] 172.18.104.228 - - [26/Sep/2018 17:14:42] "GET /upload HTTP/1.1" 200 -
[2018-09-26 17:14:42][_internal.py][line:88][INFO] 172.18.104.228 - - [26/Sep/2018 17:14:42] "GET /favicon.ico HTTP/1.1" 404 -
[2018-09-26 17:14:56][_internal.py][line:88][INFO] 172.18.104.228 - - [26/Sep/2018 17:14:56] "GET /upload HTTP/1.1" 200 -
[2018-09-27 09:48:23][_internal.py][line:88][INFO]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-09-27 13:49:56][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-27 13:50:02][log.py][line:46][INFO] {"msg":"POST请求,携带的参数不是 file "}
[2018-09-27 13:50:02][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 13:50:02] "POST /upload HTTP/1.1" 200 -
[2018-09-27 13:50:44][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-27 13:50:54][base.py][line:97][WARNING] POST http://172.18.113.112:9200/_bulk [status:N/A request:10.003s]
Traceback (most recent call last):
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='172.18.113.112', port=9200): Read timed out. (read timeout=10)
[2018-09-27 13:50:54][log.py][line:56][ERROR] ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='172.18.113.112', port=9200): Read timed out. (read timeout=10))
[2018-09-27 13:50:54][log.py][line:46][INFO] 链接数据库成功!
[2018-09-27 13:50:54][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-27 13:50:54][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-27 13:50:54][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-27 13:50:54][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 13:50:54] "POST /upload HTTP/1.1" 200 -
[2018-09-27 13:52:04][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-27 13:52:14][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-27 13:52:24][base.py][line:97][WARNING] POST http://172.18.113.112:9200/_bulk [status:N/A request:10.002s]
Traceback (most recent call last):
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/user/.virtualenvs/py3env_api/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='172.18.113.112', port=9200): Read timed out. (read timeout=10)
[2018-09-27 13:52:24][log.py][line:56][ERROR] ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='172.18.113.112', port=9200): Read timed out. (read timeout=10))
[2018-09-27 13:52:24][log.py][line:46][INFO] 链接数据库成功!
[2018-09-27 13:52:24][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-27 13:52:24][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-27 13:52:24][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-27 13:52:24][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 13:52:24] "POST /upload HTTP/1.1" 200 -
[2018-09-27 13:58:14][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-27 13:58:18][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-27 13:58:19][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.282s]
[2018-09-27 13:58:19][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.2828333377838135s
[2018-09-27 13:58:19][log.py][line:46][INFO] 链接数据库成功!
[2018-09-27 13:58:19][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-27 13:58:19][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-27 13:58:19][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-27 13:58:19][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 13:58:19] "POST /upload HTTP/1.1" 200 -
[2018-09-27 13:58:45][log.py][line:46][INFO] {"msg":"POST请求,携带的参数不是 file "}
[2018-09-27 13:58:45][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 13:58:45] "POST /upload HTTP/1.1" 200 -
[2018-09-27 14:02:18][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-27 14:02:18][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.201s]
[2018-09-27 14:02:18][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.20242953300476074s
[2018-09-27 14:02:18][log.py][line:46][INFO] 链接数据库成功!
[2018-09-27 14:02:18][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-27 14:02:18][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-27 14:02:18][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-27 14:02:18][_internal.py][line:88][INFO] 172.18.113.175 - - [27/Sep/2018 14:02:18] "POST /upload HTTP/1.1" 200 -
[2018-09-27 14:30:28][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-27 14:30:52][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-27 14:30:56][log.py][line:46][INFO] {"msg":"POST请求,携带的参数不是 file "}
[2018-09-27 14:30:56][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 14:30:56] "POST /upload HTTP/1.1" 200 -
[2018-09-27 14:31:34][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-27 14:31:34][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.232s]
[2018-09-27 14:31:34][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.23305773735046387s
[2018-09-27 14:31:34][log.py][line:46][INFO] 链接数据库成功!
[2018-09-27 14:31:34][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-27 14:31:34][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-27 14:31:34][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-27 14:31:34][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 14:31:34] "POST /upload HTTP/1.1" 200 -
[2018-09-27 14:32:52][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-27 14:33:11][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-27 14:33:16][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-27 14:33:17][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.235s]
[2018-09-27 14:33:17][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.23688936233520508s
[2018-09-27 14:33:17][log.py][line:46][INFO] 链接数据库成功!
[2018-09-27 14:33:17][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-27 14:33:17][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-27 14:33:17][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-27 14:33:17][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 14:33:17] "POST /upload HTTP/1.1" 200 -
[2018-09-27 14:34:20][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-27 14:34:26][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-27 14:34:26][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.261s]
[2018-09-27 14:34:26][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.2622494697570801s
[2018-09-27 14:34:26][log.py][line:46][INFO] 链接数据库成功!
[2018-09-27 14:34:26][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-27 14:34:26][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-27 14:34:26][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-27 14:34:26][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 14:34:26] "POST /upload HTTP/1.1" 200 -
[2018-09-27 14:38:54][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8001/ (Press CTRL+C to quit)
[2018-09-27 14:38:59][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-27 14:39:00][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.196s]
[2018-09-27 14:39:00][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.19741463661193848s
[2018-09-27 14:39:00][log.py][line:46][INFO] 链接数据库成功!
[2018-09-27 14:39:00][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-27 14:39:00][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-27 14:39:00][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-27 14:39:00][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 14:39:00] "POST /upload HTTP/1.1" 200 -
[2018-09-27 14:39:45][log.py][line:46][INFO] {"msg":"POST请求,携带的参数不是 file "}
[2018-09-27 14:39:45][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 14:39:45] "POST /upload HTTP/1.1" 200 -
[2018-09-27 14:40:55][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-27 14:40:56][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.145s]
[2018-09-27 14:40:56][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.14544320106506348s
[2018-09-27 14:40:56][log.py][line:46][INFO] 链接数据库成功!
[2018-09-27 14:40:56][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-27 14:40:56][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-27 14:40:56][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-27 14:40:56][_internal.py][line:88][INFO] 172.18.104.228 - - [27/Sep/2018 14:40:56] "POST /upload HTTP/1.1" 200 -
[2018-09-28 10:16:30][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8003/ (Press CTRL+C to quit)
[2018-09-28 10:17:02][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-28 10:17:02][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.372s]
[2018-09-28 10:17:02][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.3729708194732666s
[2018-09-28 10:17:02][log.py][line:46][INFO] 链接数据库成功!
[2018-09-28 10:17:02][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-28 10:17:02][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:17:02] "POST /upload HTTP/1.1" 200 -
[2018-09-28 10:17:19][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-28 10:17:19][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.197s]
[2018-09-28 10:17:19][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.19769644737243652s
[2018-09-28 10:17:19][log.py][line:46][INFO] 链接数据库成功!
[2018-09-28 10:17:19][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-28 10:17:19][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:17:19] "POST /upload HTTP/1.1" 200 -
[2018-09-28 10:19:54][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8003/ (Press CTRL+C to quit)
[2018-09-28 10:19:57][log.py][line:46][INFO] 获取上传文件信息:{'file': <FileStorage: 'logs.json.zip' (None)>}
[2018-09-28 10:19:57][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-28 10:19:58][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.390s]
[2018-09-28 10:19:58][log.py][line:46][INFO] json数据存储es成功! 本次共写入3条数据,用时0.39106106758117676s
[2018-09-28 10:19:58][log.py][line:46][INFO] 链接数据库成功!
[2018-09-28 10:19:58][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-28 10:19:58][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:19:58] "POST /upload HTTP/1.1" 200 -
[2018-09-28 10:25:45][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8003/ (Press CTRL+C to quit)
[2018-09-28 10:26:09][log.py][line:46][INFO] 获取上传文件信息:{}
[2018-09-28 10:26:09][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:26:09] "GET /upload HTTP/1.1" 200 -
[2018-09-28 10:26:09][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:26:09] "GET /favicon.ico HTTP/1.1" 404 -
[2018-09-28 10:50:35][log.py][line:46][INFO] 获取上传文件信息:{}
[2018-09-28 10:50:35][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:50:35] "GET /upload HTTP/1.1" 200 -
[2018-09-28 10:50:35][log.py][line:46][INFO] 获取上传文件信息:{}
[2018-09-28 10:50:35][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:50:35] "GET /upload HTTP/1.1" 200 -
[2018-09-28 10:50:35][log.py][line:46][INFO] 获取上传文件信息:{}
[2018-09-28 10:50:35][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:50:35] "GET /upload HTTP/1.1" 200 -
[2018-09-28 10:50:36][log.py][line:46][INFO] 获取上传文件信息:{}
[2018-09-28 10:50:36][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:50:36] "GET /upload HTTP/1.1" 200 -
[2018-09-28 10:50:36][log.py][line:46][INFO] 获取上传文件信息:{}
[2018-09-28 10:50:36][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:50:36] "GET /upload HTTP/1.1" 200 -
[2018-09-28 10:50:36][log.py][line:46][INFO] 获取上传文件信息:{}
[2018-09-28 10:50:36][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 10:50:36] "GET /upload HTTP/1.1" 200 -
[2018-09-28 11:37:08][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8003/ (Press CTRL+C to quit)
[2018-09-28 11:37:14][log.py][line:46][INFO] 获取上传文件信息:{'file': <FileStorage: 'logs.json.zip' (None)>}
[2018-09-28 11:37:14][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-28 11:37:14][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.291s]
[2018-09-28 11:37:14][log.py][line:46][INFO] json数据存储es成功! 本次共写入6条数据,用时0.29152941703796387s
[2018-09-28 11:37:14][log.py][line:46][INFO] 链接数据库成功!
[2018-09-28 11:37:14][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-28 11:37:14][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 11:37:14] "POST /upload HTTP/1.1" 200 -
[2018-09-28 13:33:45][_internal.py][line:88][INFO]  * Running on http://172.18.104.228:8003/ (Press CTRL+C to quit)
[2018-09-28 13:33:50][log.py][line:46][INFO] 获取上传文件信息:{'file': <FileStorage: 'logs.json.zip' (None)>}
[2018-09-28 13:33:50][log.py][line:46][INFO] 上传文件数据解析完毕!!!
[2018-09-28 13:33:51][base.py][line:83][INFO] POST http://172.18.113.113:9200/_bulk [status:200 request:0.240s]
[2018-09-28 13:33:51][log.py][line:46][INFO] json数据存储es成功! 本次共写入9条数据,用时0.24132061004638672s
[2018-09-28 13:33:51][log.py][line:46][INFO] 链接数据库成功!
[2018-09-28 13:33:51][log.py][line:46][INFO] json数据成功入库!!!
[2018-09-28 13:33:51][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/logs.json.zip
[2018-09-28 13:33:51][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/147833ee-c2e0-11e8-8f6d-00e070351684-logs.json.zip
[2018-09-28 13:33:51][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/Files/ca29ec02-c2cf-11e8-8f6d-00e070351684-logs.json.zip
[2018-09-28 13:33:51][log.py][line:46][INFO] 成功删除解压缩文件:/home/user/桌面/sort/Functions/Upload/files_unzip/logs.json
[2018-09-28 13:33:51][_internal.py][line:88][INFO] 172.18.104.228 - - [28/Sep/2018 13:33:51] "POST /upload HTTP/1.1" 200 -
